apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: payments-service-asyncapi
spec:
  type: asyncapi
  lifecycle: production
  owner: loanservices-developers
  definition: |
    asyncapi: "2.1.0"
    info:
      title: Domain Event
      version: "0.1.0"
      description: |
        Payments Service
    channels:
      store.payment-service.payment-account-change-request-value:
        subscribe:
          message:
            $ref: '#/components/messages/payment-account-change-request-value'
      request.payment-service.payment-account-change-request-value:
        subscribe:
          message:
            $ref: '#/components/messages/bank-verification-request'
      reply.payment-service.payment-account-change-request-value:
        subscribe:
          message:
            $ref: '#/components/messages/bank-verification-reply'
    components:
      messages:
        payment-account-change-request-value:
          title: Domain Event
          schemaFormat: 'application/vnd.apache.avro+json;version=1.9.0'
          payload:
            $ref: "https://schema-registry.dev.aws-ue1.happymoney.com/subjects/store.payment-service.payment-account-change-request-value/versions/latest/schema"
